### ISSUE TITLE
!!! urgent, I cannot find `From Skeleton to Base Mesh` and `Mesh Refinement` code

### ISSUE THREAD

**Issue by Leerw** [tangjiapeng/SkeletonBridgeRecon#1]
Hi, thanks for your kind sharing and impressive CVPR work.
But I have a question after reading your codes, I could not find any code related to the sections `From Skeleton to Base Mesh` and `Mesh Refinement` mentioned in your paper, is there somewhere I missed? Could you please point it out for me?

**Comment by tangjiapeng** [comment]
I have release all code. If you have some questions, please feel  free to contact me! You could email me directly.
