### ISSUE TITLE
Is stage 3(Mesh Deformation) in the pipeline useful ?

### ISSUE THREAD

**Issue by DreamBlack** [tangjiapeng/SkeletonBridgeRecon#3]
Is stage 3(Mesh Deformation) in the pipeline useful?
I did not find any figures or tables in the paper which proves the effect of stage 3.

**Comment by tangjiapeng** [comment]
Mesh deformation is certainly useful in our pipeline, as it deform the skeletal mesh(extracted from skeletal volume) to fit the target surface.
