### ISSUE TITLE
The ShapeNet-Skeleton dataset is extracted from ShapeNet v1 or v2 ?

### ISSUE THREAD

**Issue by Neyeee** [tangjiapeng/SkeletonBridgeRecon#5]
Hi,

I just observed that the scale and orientation of ShapeNet-Skeleton points are different from the ShapeNet v2 models. Just want to know which ShapeNet version the Skeleton dataset is extracted from?

Many thanks for your help!

**Comment by tangjiapeng** [comment]
the skeletons is extracted from ShapeNet v1 models.
